In [1]:
import numpy as np

In [2]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])

In [3]:
len(data)

10

In [4]:
np.average(data)

5.5

In [5]:
np.mean(data)

5.5

In [12]:
var = np.var(data)

In [10]:
sd = np.std(data)

In [13]:
np.sqrt(var)

2.8722813232690143

In [14]:
sd

2.8722813232690143

In [16]:
np.sort(data)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.max(data)

10

In [18]:
data *2

array([18,  4,  6,  8, 20, 12, 14, 16,  2, 10])

In [19]:
data[1]

2

In [20]:
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [21]:
data.sort()

In [22]:
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.random.seed(0)

In [24]:
rnd_data = np.random.randn(10)

In [25]:
rnd_data

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [26]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])