In [29]:
import tensorflow as tf

In [30]:
a = tf.constant([[1,2],[3,4]], name='a')
b = tf.constant([[1], [2]], name = 'b')
c = tf.matmul(a, b)

In [31]:
print('shape of a: ', a.shape)
print('shape of b: ', b.shape)
print('shape of c: ', c.shape)


shape of a:  (2, 2)
shape of b:  (2, 1)
shape of c:  (2, 1)


In [32]:
with tf.Session() as sess:
    print('a=\n' , sess.run(a))
    print('b=\n' , sess.run(b))
    print('c=\n' , sess.run(c))

a=
 [[1 2]
 [3 4]]
b=
 [[1]
 [2]]
c=
 [[ 5]
 [11]]


In [33]:
a = tf.placeholder(shape= (None, 2), dtype=tf.int32, name='a')

In [34]:
with tf.Session() as sess:
    print('--[[1,2]]--を代入')
    print('a=' ,sess.run(a, feed_dict={a:[[1,2]]}))
    print('\n--[[1,2],[3,4]]を代入--')
    print('a=' ,sess.run(a, feed_dict={a:[[1,2], [3,4]]}))

--[[1,2]]--を代入
a= [[1 2]]

--[[1,2],[3,4]]を代入--
a= [[1 2]
 [3 4]]


In [35]:
a = tf.Variable(1, name='a')
b = tf.assign(a, a+1)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    print('一回目 b= ', sess.run(b))
    print('二回目 b= ', sess.run(b))


with tf.Session() as sess:
    print('新しいセッション')
    sess.run(tf.global_variables_initializer())
    
    
    print('一回目 b= ', sess.run(b))
    print('二回目 b= ', sess.run(b))

一回目 b=  2
二回目 b=  3
新しいセッション
一回目 b=  2
二回目 b=  3


In [36]:
a = tf.Variable(1, name='a')
b = tf.assign(a, a+1)

saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    print('一回目 b= ', sess.run(b))
    print('二回目 b= ', sess.run(b))
    
    saver.save(sess, 'model/moled.ckpt')
    
saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    saver.restore(sess, save_path= 'model/model.ckpt')
    print('二回目 b= ', sess.run(b))

一回目 b=  2
二回目 b=  3


ValueError: The passed save_path is not a valid checkpoint: model/model.ckpt

In [37]:
import matplotlib.pyplot as plt

In [38]:
x =tf.Variable(0., name='x')

func = (x-1)**2

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)

train_step = optimizer.minimize(func)


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(20):
        sess.run(train_step)
        
    print('x= ', sess.run(x))

x=  0.98847073


In [39]:
x =tf.Variable(0., name='x')

func = (x-1)**2

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)

train_step = optimizer.minimize(func)

t_ = []
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(20):
        t_.append(sess.run(train_step))
        
        
    print('x= ', sess.run(x))

x=  0.98847073


In [40]:
t_

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [25]:
import numpy as np