In [1]:
import scipy.linalg as linalg
from scipy.optimize import minimize_scalar

In [2]:
import numpy as np

In [5]:
matrix = np.array([[1,-1,-1],
                  [-1,1,-1],
                  [-1,-1,1]])

In [6]:
print('行列式')
print(linalg.det(matrix))

行列式
-4.0


In [7]:
print('逆行列')
print(linalg.inv(matrix))

逆行列
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [8]:
print(matrix.dot(linalg.inv(matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
eig_val, eig_vec = linalg.eig(matrix)

In [10]:
print("固有値", eig_val)
print("固有ベクトル ", eig_vec)

固有値 [-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル  [[ 0.57735027  0.81649658  0.40824829]
 [ 0.57735027 -0.40824829 -0.81649658]
 [ 0.57735027 -0.40824829  0.40824829]]


## newton method

In [11]:
def my_func(x):
    return(x**2 + 2*x +1)

In [12]:
from scipy.optimize import newton

In [14]:
print(newton(my_func, 0))

-0.9999999852953906


In [15]:
minimize_scalar(my_func, method="Brent")

     fun: 0.0
    nfev: 9
     nit: 4
 success: True
       x: -1.0000000000000002

## execr

In [16]:
mat = np.array([[1,2,3],[1,3,2],[3,1,2]])

In [17]:
linalg.det(mat)

-12.000000000000002

In [18]:
linalg.inv(mat)

array([[-0.33333333,  0.08333333,  0.41666667],
       [-0.33333333,  0.58333333, -0.08333333],
       [ 0.66666667, -0.41666667, -0.08333333]])

In [20]:
linalg.eig(mat)

(array([ 6.        +0.j, -1.41421356+0.j,  1.41421356+0.j]),
 array([[-0.57735027, -0.72236645,  0.16041816],
        [-0.57735027, -0.14290228, -0.81090869],
        [-0.57735027,  0.67658381,  0.56275492]]))