## vector

In [1]:
import numpy as np

In [10]:
from sympy import *

In [11]:
init_printing()

In [2]:
b = np.array([1,3])
c = np.array([4,2])

In [3]:
b.dot(c)

10

In [4]:
np.dot(b,c)

10

In [5]:
A = np.array([[1,2],[3,4]])

In [6]:
np.dot(A,b)

array([ 7, 15])

In [7]:
b+c

array([5, 5])

In [8]:
b-c

array([-3,  1])

## vector size

In [9]:
np.linalg.norm(b)

3.1622776601683795

In [13]:
from IPython.display import display, Math

In [14]:
display(Math(|a|= sqrt(a_0**2 + a_1**2)))

SyntaxError: invalid syntax (<ipython-input-14-eceba84097ea>, line 1)

In [15]:
import matplotlib.pyplot as plt

In [16]:
def f(w0, w1):
    return w0 **2 + 2* w0*w1 +3

In [17]:
def df_dw0(w0, w1):
    return 2*w0 + 2*w1

def df_dw1(w0, w1):
    return 2*w0 + 0*w1

In [18]:
w_range = 2
dw = 0.25
w0 = np.arange(-w_range, w_range+ dw, dw)
w1 = np.arange(-w_range, w_range+ dw, dw)
wn = w0.shape[0]

In [19]:
ww0, ww1 = np.meshgrid(w0, w1)